apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-feed-qa
  name: backend-feed-qa
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: backend-feed-qa